##' Get Mean / Mode / Median State
##' 
##' Get Mean / Mode / Median state of multi-state chains. Note that for 3 state models, the mode is preferred, as the
##' mean and median for a split between states 1 and 3 would be state 2. If the data used
##' to fit the JAGS model is provided (a data frame generated by \code{GetVT} in \code{\link[bcpa:bcpa-package]{bcpa}}), then a data frame containing the state and time for
##' each step in the track is returned. Otherwise, just the vector of states is returned.
##' 
##' 
##' @param jagsResults An \code{\link[=rjags-class]{rjags}} result
##' @param data (optional) The data used to fit the \code{jagsResults} containing a \code{T.POSIX} column.
##' @return Return vector of (or data frame including time) respective mean, median or mode of states for each step
##'
##' 
##' @author Chloe Bracis

getMeanStates <- function(jagsResults, data = NULL)
{
	if (class(jagsResults) != "rjags") stop("jagsResults parameter must be an rjags object")
	if (!("idx" %in% jagsResults$parameters.to.save)) stop("Must record idx parameter to get states")
	
	means <- apply(.getIdxArray(jagsResults), 3, mean)
  
  if ( !is.null(data) )
  {
    if (nrow(data) != length(means)) stop("Provided data must be same length as data used to fit jagsResults object")
    means <- data.frame(State = means, Time = data$T.POSIX)
  }
  
	return(means)
}
