##' Get iteration similar to mode of multi-state chains
##' 
##' Get the assigned states from the iteration from the chain most similar to the mode state at each step. If the data used
##' to fit the JAGS model is provided (a data frame generated by \code{GetVT} in \code{\link[bcpa:bcpa-package]{bcpa}}), then a data frame containing the state and time for
##' each step in the track is returned. Otherwise, just the vector of states is returned.
##' 
##' @param jagsResults An \code{\link[=rjags-class]{rjags}} result
##' @param data (optional) The data used to fit the \code{jagsResults} containing a \code{T.POSIX} column.
##' @return Return a vector (or data frame including time) of the states from the iteration most closely matching the mode states.
##' @seealso \link{getModeStates}
##' @author Chloe Bracis


getIterationSimilarModeStates <- function(jagsResults, data = NULL)
{
  modes <- getModeStates(jagsResults)
  idxArray <- .getIdxArray(jagsResults)
  dim(idxArray) <- c(dim(idxArray)[1] * dim(idxArray)[2], dim(idxArray)[3]) # combine chains so we have a matrix instead of an array
  error <- apply(idxArray, 1, function(x) sum((x - modes)^2))
  similarIdx <- which.min(error)
  iteration <- idxArray[similarIdx,]
    
  if ( !is.null(data) )
  {
    if (nrow(data) != length(iteration)) stop("Provided data must be same length as data used to fit jagsResults object")
    iteration <- data.frame(State = iteration, Time = data$T.POSIX)
  }
  
  return(iteration)
}
